src/views/front.py
# -*- coding: utf-8 -*-
"""
    views.front
    ~~~~~~~~~~~

    Frontend view functions.

    :copyright: (c) 2019 by staugur.
    :license: BSD 3-Clause, see LICENSE for more details.
"""

from flask import (
    Blueprint,
    render_template,
    make_response,
    redirect,
    url_for,
    current_app,
    Response,
    g,
    abort,
)
from utils.web import (
    admin_apilogin_required,
    anonymous_required,
    login_required,
    check_activate_token,
    dfr,
)
from utils.tool import is_true, rsp, string_types
from utils._compat import PY2, text_type

bp = Blueprint("front", "front")


@bp.route("/")
def index():
    return render_template("public/index.html")


@bp.route("/login")
@anonymous_required
def login():
    if g.cfg.site_auth:
        so = current_app.extensions["hookmanager"].proxy(g.cfg.site_auth)
        if so and hasattr(so, "login_handler"):
            result = so.login_handler()
            if result and isinstance(result, Response):
                return result
    return render_template("public/login.html")


@bp.route("/logout")
@login_required
def logout():
    if g.cfg.site_auth:
        so = current_app.extensions["hookmanager"].proxy(g.cfg.site_auth)
        if so and hasattr(so, "logout_handler"):
            result = so.logout_handler()
            if result and isinstance(result, Response):
                return result
    res = make_response(redirect(url_for("front.index")))
    res.set_cookie(key="dSid", value="", expires=0)
    return res


@bp.route("/register")
@anonymous_required
def register():
    if is_true(g.cfg.register):
        return render_template("public/register.html")
    else:
        return abort(404)


@bp.route("/control/myself")
@login_required
def my():
    return render_template("control/my.html")


@bp.route("/control/admin")
@admin_apilogin_required
def admin():
    return render_template("control/admin.html")


@bp.route("/picbed.user.js")
@bp.route("/sapic.user.js")
def userscript():
    if g.signin and is_true(g.userinfo.ucfg_userscript):
        resp = make_response(render_template("public/userscript.js"))
        resp.headers["Content-type"] = "application/javascript; charset=utf-8"
        return resp
    else:
        return abort(404)


@bp.route("/activate/<token>")
def activate(token):
    res = dfr(check_activate_token(token))
    if res["code"] == 0:
        data = res["data"]
        Action = data["Action"]

        if Action == "verifyEmail":
            username = data["username"]
            checkmail = data["email"]
            uk = rsp("account", username)
            usermail = g.rc.hget(uk, "email")
            success = False
            url = url_for("front.my") if g.signin else url_for("front.login")
            if checkmail == usermail:
                g.rc.hset(uk, "email_verified", 1)
                success = True
            return render_template("public/go.html", url=url, success=success)

        elif Action == "resetPassword":
            username = data["username"]
            return render_template(
                "public/forgot.html", is_reset=True, token=token, user=username
            )

    else:
        name = res["msg"]
        if PY2 and not isinstance(name, text_type):
            name = name.decode("utf-8")
        return render_template("public/error.html", code=res["code"], name=name)


@bp.route("/forgot")
@anonymous_required
def forgot():
    return render_template("public/forgot.html")


@bp.route("/extendpoint/<hook_name>/", defaults=dict(route_name=None))
@bp.route("/extendpoint/<hook_name>/<route_name>")
def ep(hook_name, route_name):
    obj = current_app.extensions["hookmanager"].proxy(hook_name)
    if obj and hasattr(obj, "route"):
        rule = obj.route()
        if isinstance(rule, string_types):
            return rule
        elif isinstance(rule, dict) and route_name in rule:
            rst = rule[route_name]
            if callable(rst):
                if not isinstance(rst, Response):
                    return rst()
            return rst
    return abort(404)


@bp.route("/feed")
@login_required
def feed():
    pipe = g.rc.pipeline()
    uk = rsp("index", "user", g.userinfo.username)
    fields = ["title", "filename", "ctime", "user", "src", "is_video"]
    for sha in g.rc.smembers(uk):
        pipe.hmget(rsp("image", sha), *fields)
    result = pipe.execute()
    data = [dict(zip(fields, i)) for i in result if i]
    xml = render_template(
        "public/feed.xml",
        items=sorted(data, key=lambda k: int(k.get("ctime") or 0), reverse=True)[:10],
    )
    response = make_response(xml)
    response.headers["Content-Type"] = "application/xml"
    return response


@bp.route("/publish")
def publish():
    gfs = [
        dict(field="title_name", name=u"站点名称", default=g.site_name),
        dict(field="beian", name=u"备案", default=""),
        dict(field="upload_field", name=u"上传字段", default="picbed"),
        dict(field="cors", name=u"跨域共享源站", default=""),
    ]
    return render_template("public/publish.html", gfs=gfs)

src/templates/layout/base.html
<!DOCTYPE html>
<html>

<head>
    {% include "ref/header.html" %}
    <title>{% block LayoutTitle %}{% endblock %} | {{ g.site_name }}</title>
    <link href="{{ url_for('static', filename='layui/css/layui.css', v=Version) }}" rel="stylesheet" media="all">
    <link rel="stylesheet" type="text/css" href="https://static.saintic.com/iconfont/iconfont.min.css">
    <style>
        * {
            padding: 0;
            margin: 0;
        }
        body, html {
            height: 100%;
            background-color: #F6F6F6;
        }
        /*暂时屏蔽全站背景图
        html {
            background-image: url("{{ g.userinfo.ucfg_bg_mg or g.site.bg_mg or url_for('static', filename='img/bg5.jpg') }}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            font-family: "Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "MicrosoftYaHei", "WenQuanYi Micro Hei", sans-serif;
        }
        */
        /*全局页面导航栏*/
        .layui-nav .layui-nav-item a {
            color: #23262E;
            /*font-weight: bold;*/
        }
        .layui-nav .layui-nav-item a:hover {
            color: #23262E;
        }
        .layui-nav .layui-nav-item {
            /*fix +0.5*/
            line-height: 60.5px;
        }
        /*公开页面布局*/
        .layui-layout-admin .layui-header {
            background-color: transparent;    
        }
        .layui-layout-admin .layui-body {
            left: 0px;
            text-align: center;
        }
        .layui-layout-admin .layui-footer {
            left: 0px;
            /*color: #999;*/
            text-align: center;
            background-color: transparent;
        }
        .layui-layout-admin .layui-logo img {
            height: 80%;
        }
        /*全站公告栏*/
        .bulletin-board {
            padding: 10px;
            max-height: 60px;
            overflow: hidden;
        }
        .bulletin-board a {
            color: #01AAED;
        }
        .bulletin-board img {
            max-height: 60px;
        }
        /*优化下单独input*/
        .my-input {
            height: 24px;
            border-width: 1px;
            border-style: solid;
            background-color: #fff;
            border-radius: 2px;
        }
        .my-input::placeholder {
            color: #c2c2c2;
        }
        /*消息组件*/
        [class^="msg-icon-"],
        [class*="msg-icon-"] {
            font-style: normal;
            font-weight: normal;
            font-variant: normal;
            text-transform: none;
            line-height: 1;
            vertical-align: middle;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
        .msg-icon-success {
            color: #00a854;
        }
        .msg-icon-info {
            color: #108ee9;
        }
        .msg-icon-warn {
            color: #ffbf00;
        }
        .msg-icon-error {
            color: #f04134;
        }
        .m-message {
            pointer-events: none;
            /*可以点击下面的元素*/
            position: fixed;
            overflow: hidden;
            z-index: 1001;
        }
        .c-message-notice {
            text-align: center;
            margin: 10px 10px;
        }
        .m_content {
            font-family: "microsoft yahei", "宋体";
            display: inline-block;
            border: 1px solid #eee;
            border-radius: 5px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, .2);
            color: #555;
            text-align: left;
            max-width: 90%;
            padding: 5px 10px 5px 15px;
            background-color: #fff;
        }
        .m_content span {
            vertical-align: middle;
            margin-left: 5px;
        }
        @media screen and (max-width: 400px) {
            .layui-layout-admin .layui-logo {
                width: auto;
                height: auto;
            }
            .layui-layout-admin .layui-logo img {
                max-width: 100px;
            }
        }
    </style>
    {% block LayoutHead %}{% endblock %}
</head>

<body>
{% if g.site.bulletin %}
<div class="layui-bg-cyan bulletin-board">{{ g.site.bulletin|safe }}</div>
{% endif %}
{% block LayoutBody %}{% endblock %}
<script src="{{ url_for('static', filename='layui/layui.all.js', v=Version) }}"></script>
<script>
    layui.config({
        base: "/static/mymod/",
        version: "{{ Version }}"
    }).use('picbed', function() {
        var $ = layui.jquery,
            layer = layui.layer;
        $("#about").on("click",function(){
            layer.open({
                type: 2,
                title: "关于本站",
                closeBtn: false,
                area: ['350px', '400px'],
                btn: '关闭',
                btnAlign: 'c',
                shade: 0.1,
                shadeClose: true,
                content: ["{{ url_for('front.publish') }}"]
            });
        });
    });
</script>
{% block LayoutScript %}{% endblock %}
</body>

</html>

src/templates/layout/control.html
{% extends "layout/base.html" %}

{% block LayoutTitle %}{% block title %}{% endblock %} - 控制台{% endblock %}

{% block LayoutHead %}
<style>
    /*控制台页面布局*/
    .header {
        height: 59px;
        background-color: transparent;
    }
    .layui-logo img {
        width: auto;
        height: 50px;
        padding-top: 5px;
    }
    .header .layui-nav {
        position: absolute;
        right: 5px;
        top: 0;
        padding: 0;
        background: none;
    }
    .footer {
        color: #333;
        /*position: fixed;*/
        left: 0;
        right: 0;
        bottom: 0;
        padding: 3px 1em 3px 1em;
        text-align: center;
    }
</style>
{% block head %}{% endblock %}
{% endblock %}

{% block LayoutBody %}
<div>
    <div class="layui-header header">
        <div class="layui-container-fluid">
            {% include "ref/nav.html" %}
        </div>
    </div>
    {% block content %}{% endblock %}
    <div class="layui-footer footer">
        <div class="layui-container">
            {% include "ref/footer.html" %}
        </div>
    </div>
</div>
{% endblock %}

{% block LayoutScript %}
{% block script %}{% endblock %}
{% endblock %}

src/templates/layout/public.html
{% extends "layout/base.html" %}

{% block LayoutTitle %}{% block title %}{% endblock %}{% endblock %}

{% block LayoutHead %}
<style>
    /*公开页面背景图*/
    body, html {
        overflow: hidden;
    }
    html {
        background-image: url("{{ g.userinfo.ucfg_bg_mg or g.site.bg_mg or url_for('static', filename='img/bg5.jpg') }}");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        font-family: "Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "MicrosoftYaHei", "WenQuanYi Micro Hei", sans-serif;
    }
    body {
        background-color: rgba(255, 255, 255, {{ g.userinfo.ucfg_bg_ransparency or g.site.bg_ransparency or 0.5|float }});
    }
    @media screen and (max-width: 500px) {
        html {
            background-image: url("{{ g.userinfo.ucfg_bg_mobile or g.site.bg_mobile or url_for('static', filename='img/mbg1.jpg') }}");
        }
    }
    .layui-layout-admin .layui-footer {
        line-height: 18px;
    }
</style>
{% block head %}{% endblock %}
{% endblock %}

{% block LayoutBody %}
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        {% include "ref/nav.html" %}
    </div>
    <div class="layui-body">
        <!-- 正文 -->
        {% block content %}{% endblock %}
    </div>
    <div class="layui-footer">
        {% include "ref/footer.html" %}
    </div>
</div>
{% endblock %}

{% block LayoutScript %}
{% block script %}{% endblock %}
{% endblock %}